import { revealCard, gatherCards } from "controllers/motion_helpers"
import { Controller } from "@hotwired/stimulus"
export default class extends Controller {
 static values={payload:Object}
 connect(){
 const events=new AbortController();let toastTimer;
 const listen=(type,fn)=>this.element.addEventListener(type,fn,{signal:events.signal});
 const catalogue=this.payloadValue.cards;
 const token=document.querySelector('meta[name="csrf-token"]').content;
 const save=async(ids,button,stackId=null)=>{button.disabled=true;try{const response=await fetch('/wallet_items/save_browse',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-Token':token},body:JSON.stringify({card_ids:ids,stack_id:stackId})});const data=await response.json();if(response.status===401){location.href=data.sign_in_url;return}if(!response.ok)throw new Error(data.error||'Could not save. Try again.');ids.forEach(id=>saved.add(id));await gatherCards(this.element.querySelectorAll('dialog[open] .credit, .product .credit'),button);button.textContent='Added to Planned ✓'}catch(error){toast(error.message)}finally{button.disabled=false}};
let browseMode=new URLSearchParams(location.search).get('tab')==='stacks'?'stacks':'cards';let layout='list',query='',category=(new URLSearchParams(location.search).get('category')||'All'),fee='all',foreign=false,sort='featured',compared=new Set(),saved=new Set();const money=n=>n==null?'Check issuer terms':'$'+Number(n).toLocaleString();const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function art(c){if(c.imageUrl)return `<div class="credit has-card-image"><img class="card-image" src="${esc(c.imageUrl)}" alt="" loading="lazy" decoding="async"></div>`;let i=catalogue.indexOf(c),colors=['#681c28','#444647','#b7b9b9','#e5e1d7'];return `<div class="credit" style="--metal:${colors[i%4]};--fg:${i%4<2?'white':'#222'}"><span class="brand">shuffl.</span><span class="chip"></span><span class="name">${esc(c.name)}</span></div>`}

const stacks=this.payloadValue.stacks.map(s=>{const cards=s.ids.map(id=>catalogue.find(c=>c.id===id)).filter(Boolean);return {...s,cards,annualFee:cards.some(c=>c.annualFee==null)?null:cards.reduce((sum,c)=>sum+c.annualFee,0),foreignTransactionFee:cards.some(c=>c.foreignTransactionFee===true)?true:cards.some(c=>c.foreignTransactionFee==null)?null:false}});
function stackArt(s){return `<div class="stack-art">${s.cards.map((c,i)=>`<div style="--i:${i}">${art(c)}</div>`).join('')}</div>`}
function stackProduct(s){return `<article class="product stack-product"><button class="art" data-stack="${s.id}" aria-label="Explore ${esc(s.name)}">${stackArt(s)}<span class="hover-explore" aria-hidden="true">Explore stack ↗</span></button><div><div class="issuer">${s.cards.length} CARDS · ${s.issuer}</div><h2>${esc(s.name)}</h2><p class="perks">${s.intro}</p><p class="stack-names">${s.cards.map(c=>esc(c.name)).join(' · ')}</p></div><div class="metrics"><div><strong>${s.cards.length} cards</strong><small>Different jobs, one wallet</small></div><div><strong class="fee">${money(s.annualFee)}</strong><small>Total annual fees</small></div></div><div class="actions"></div></article>`}
function stackDetail(id){const s=stacks.find(s=>s.id===id);show(esc(s.name),`<p>${s.intro}</p><div class="metrics"><div><strong class="fee">${money(s.annualFee)}</strong><small>Combined ongoing annual fees · USD</small></div></div><p class="note">Before introductory waivers or conditional credits.</p><div class="stack-members">${s.cards.map(c=>`<a class="stack-member" href="${c.url}"><div class="art">${art(c)}</div><div><h3>${esc(c.name)}</h3><p>${esc(s.roles[c.id]||c.rewardSummary)}</p><span class="fee">${money(c.annualFee)} annual fee</span></div></a>`).join('')}</div>${s.notes?`<h3>How to use this stack</h3><p>${esc(s.notes)}</p>`:''}<p><a href="${s.url}">Full stack details ↗</a></p><p><button class="primary" data-savestack="${s.id}">Add stack to Planned</button></p><p class="note">This saves a shortlist. No applications are submitted. Cards already in your wallet stay as they are.</p>`)}

function bonus(c){return c.welcomeOffer?esc(c.welcomeOffer):'<a href="'+c.url+'">See issuer offers ↗</a>'}
function product(c){return `<article class="product"><button class="art" data-detail="${c.id}" aria-label="Explore ${esc(c.name)}">${art(c)}<span class="hover-explore" aria-hidden="true">Explore card ↗</span></button><div><div class="issuer">${esc(c.issuer)}${c.cardNetwork?' · '+esc(c.cardNetwork):''}</div><h2>${esc(c.name)}</h2><p class="perks">${esc(c.perks.slice(0,2).join(' · '))}</p></div><div class="metrics"><div><strong>${esc(c.valueProfile.value)}</strong><small>${esc(c.valueProfile.label)}</small>${c.valueProfile.conditions?`<small>${esc(c.valueProfile.conditions)}</small>`:''}</div><div><strong class="fee">${money(c.annualFee)}</strong><small>Annual fee</small></div></div><div class="actions"><label class="compare-label"><input type="checkbox" data-compare="${c.id}" ${compared.has(c.id)?'checked':''}> Compare</label></div></article>`}
function filtered(){let list=(browseMode==='stacks'?stacks:catalogue).filter(c=>(c.name+' '+c.issuer).toLowerCase().includes(query.toLowerCase())&&(category==='All'||c.categories.includes(category.toLowerCase()))&&(fee==='all'||(c.annualFee!=null&&c.annualFee<=+fee))&&(!foreign||c.foreignTransactionFee===false));if(sort==='fee')list.sort((a,b)=>(a.annualFee??Infinity)-(b.annualFee??Infinity));if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function results(){let list=filtered();document.getElementById('count').textContent=list.length+' '+browseMode;document.getElementById('results').innerHTML=list.length?list.map(browseMode==='stacks'?stackProduct:product).join(''):'<div class="empty"><h2>No cards match just yet.</h2><p>Try another search or clear your filters.</p><button data-reset>Clear filters</button></div>';document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.category===category));tray()}
function render(){return `<main class="${layout}"><div class="hero"><div><span class="eyebrow">The card collection</span><h1>${layout==='gallery'?'find your next <span class="keyword-emphasis">card.</span>':'a little more <span class="keyword-emphasis">rewarding.</span>'}</h1><p>${layout==='gallery'?'Explore the possibilities. Keep what fits.':'Find the right fit, with the details side by side.'}</p><div class="browse-tabs" role="tablist" aria-label="Browse collection"><button role="tab" data-mode="cards" aria-selected="${browseMode==='cards'}">Cards</button><button role="tab" data-mode="stacks" aria-selected="${browseMode==='stacks'}">Stacks</button></div></div><aside>Not sure where to start?<br>Let your spending lead the way.<br><button class="link" data-quiz>Find my match ↗</button></aside></div><div class="controls"><div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input id="search" aria-label="Search cards or issuers" placeholder="Search cards or issuers" value="${esc(query)}"></label><button id="filter-toggle" aria-expanded="${category!=='All'}">Filters +</button><select id="sort" class="sort" aria-label="Sort cards"><option value="featured">Catalogue order</option><option value="fee">Lowest annual fee</option><option value="name">Name A–Z</option></select></div><div class="filter-extra" id="extra" ${category==='All'?'hidden':''}><div class="category-filter"><span class="muted">Category</span><div class="chips">${['All','Travel','Cashback','Dining','Student'].map(t=>`<button data-category="${t}" aria-pressed="${t===category}">${t}</button>`).join('')}</div></div><label>Annual fee <select id="fee"><option value="all">Any fee</option><option value="0">No annual fee</option><option value="100">Up to $100</option></select></label><label><input id="foreign" type="checkbox"> No foreign transaction fees</label><button class="link" data-reset>Reset</button></div></div><div class="results-top"><span id="count">${filtered().length} ${browseMode}</span><span>${browseMode==='stacks'?'Compare recorded terms':'Choose up to 3 cards to compare'}</span></div>${layout==='list'?`<div class="list-head"><span>${browseMode==='stacks'?'THE STACK':'THE CARD'}</span><span>WHAT IT OFFERS</span><span>REWARDS & FEES</span><span>${browseMode==='stacks'?'':'COMPARE'}</span></div>`:''}<div class="results" id="results">${filtered().map(browseMode==='stacks'?stackProduct:product).join('')}</div><p class="note">Recorded issuer research for the demo. Rates have conditions and may change. Explore supported cashback estimates from your quiz results. Saved cards appear in Planned in My Wallet.</p></main>`}
function reset(){query='';category='All';fee='all';foreign=false;sort='featured';compared.clear();tray()}
function tray(){const el=document.getElementById('tray');el.hidden=!compared.size;el.innerHTML=`<span>${compared.size} of 3 selected</span><button class="primary" data-showcompare ${compared.size<2?'disabled':''}>Compare cards</button><button class="link" data-clear>Clear</button>`}
function toast(t){document.getElementById('toast').textContent=t;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.getElementById('toast').textContent='',3000)}
function show(title,body){const m=document.getElementById('modal');m.innerHTML=`<div class="dialog-top"><div><span class="eyebrow">Take a closer look</span><h2>${title}</h2></div><button data-close aria-label="Close details">✕</button></div>${body}`;m.showModal()}
function detail(id){const c=catalogue.find(c=>c.id===id);show(esc(c.name),`<div class="detail-layout"><div><div class="art">${art(c)}</div><p>${esc(c.issuer)}${c.cardNetwork?' · '+esc(c.cardNetwork):''}</p><span class="fee">${money(c.annualFee)} annual fee</span></div><div>${c.welcomeOffer?`<h3>Welcome offer and requirements</h3><p>${bonus(c)}</p>`:''}<div class="rates">${c.rewardRules.map(r=>`<p><strong>${esc(r.rate)} ${esc(r.unit.replaceAll('_',' '))} — ${esc(r.category)}</strong><br>${esc(r.conditions||'')}</p>`).join('')||'<p>'+esc(c.valueProfile.detail)+'</p>'}</div><ul>${c.perks.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><p><a href="${c.url}">Full terms and issuer sources ↗</a></p><button class="primary" data-save="${id}">${saved.has(id)?'Added to Planned ✓':'Add to Planned'}</button><p class="note">Saved to Planned in My Wallet.</p></div></div>`)}
listen('input',e=>{if(e.target.id==='search'){query=e.target.value;results()}});
listen('change',e=>{const t=e.target;if(t.id==='sort')sort=t.value;if(t.id==='fee')fee=t.value;if(t.id==='foreign')foreign=t.checked;if(t.dataset.compare){if(t.checked&&compared.size>=3){t.checked=false;toast('Choose up to three cards to compare.');return}t.checked?compared.add(t.dataset.compare):compared.delete(t.dataset.compare)}if(t.dataset.compare)tray();else if(['sort','fee','foreign'].includes(t.id))results()});
listen('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.mode){browseMode=b.dataset.mode;const url=new URL(location);url.searchParams.set('tab',browseMode);history.replaceState(null,'',url);reset();document.getElementById('stage').innerHTML=render();return}if(b.dataset.stack){stackDetail(b.dataset.stack);return}if(b.dataset.savestack){save(stacks.find(s=>s.id===b.dataset.savestack).ids,b,b.dataset.savestack);return}if(b.dataset.category){category=b.dataset.category;results()}if(b.id==='filter-toggle'){const el=document.getElementById('extra');el.hidden=!el.hidden;b.setAttribute('aria-expanded',!el.hidden)}if(b.hasAttribute('data-reset')){reset();document.getElementById('search').value='';document.getElementById('fee').value='all';document.getElementById('foreign').checked=false;document.getElementById('sort').value='featured';results()}if(b.dataset.detail)revealCard(b.querySelector('.credit'),()=>detail(b.dataset.detail),()=>document.querySelector('#modal .credit'));if(b.hasAttribute('data-close'))document.getElementById('modal').close();if(b.dataset.save){save([b.dataset.save],b)}if(b.hasAttribute('data-clear')){compared.clear();results()}if(b.hasAttribute('data-showcompare')){const cards=catalogue.filter(c=>compared.has(c.id));show('Find your fit.',`<div style="overflow:auto"><table><thead><tr><th></th>${cards.map(c=>`<th>${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${[['Annual fee',c=>'<span class="fee">'+money(c.annualFee)+'</span>'],['Welcome bonus',c=>'<span class="reward">'+bonus(c)+'</span>'],['Recorded rewards',c=>esc(c.rewardSummary)],['Full terms',c=>'<a href="'+c.url+'">Rates, conditions and sources ↗</a>'],['Foreign fees',c=>c.foreignTransactionFee==null?'Check issuer terms':c.foreignTransactionFee?'Applies':'None'],['Top perks',c=>c.perks.map(esc).join('<br>')]].map(([label,fn])=>`<tr><th>${label}</th>${cards.map(c=>`<td>${fn(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`)}if(b.hasAttribute('data-quiz'))show('Start with your spending.',`<p>The quiz matches cards to your spending, preferences, and goals.</p><p style="margin-top:20px"><a href="/quiz_responses/new">Open the Shuffle quiz ↗</a></p>`)});

document.getElementById('stage').innerHTML=render();
this.cleanup=()=>{events.abort();clearTimeout(toastTimer);document.getElementById('modal')?.close()};
 }
 disconnect(){this.cleanup?.()}
}
