---
application.css:
  hex: 43
  fonts: 0
assistant.css:
  hex: 5
  fonts: 0
browse.css:
  hex: 24
  fonts: 0
detail.css:
  hex: 7
  fonts: 0
footer.css:
  hex: 0
  fonts: 0
home.css:
  hex: 22
  fonts: 0
login.css:
  hex: 44
  fonts: 0
product_motion.css:
  hex: 8
  fonts: 0
quiz.css:
  hex: 17
  fonts: 0
results.css:
  hex: 11
  fonts: 0
spinning_buttons.css:
  hex: 8
  fonts: 0
theme.css:
  hex: 31
  fonts: 0
wallet.css:
  hex: 29
  fonts: 0
z_mobile.css:
  hex: 1
  fonts: 0
